version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:${MARIADB_VERSION}'
    volumes:
      - 'mariadb_data:/bitnami'
    environment:
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
  wordpress:
    build:
      context: .
    ports:
      - '8080:80'
      - '8443:443'
    volumes:
      - '../wp-content/themes/beonepage/:/bitnami/wordpress/wp-content/themes/beonepage/'
    depends_on:
      - mariadb
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
